#######################################################################################
# Book settings
title: Python Packages
author: Tomas Beuzen & Tiffany Timbers
copyright: "2021"
logo: images/py-pkgs-hex.png
repository:
  url: https://github.com/py-pkgs/py-pkgs
  path_to_book: "py-pkgs/"  # A path to your book's folder, relative to the repository root.
  branch: master  # Which branch of the repository should be used when creating links
exclude_patterns: [bookdown, _build]

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions: [sphinx-prompt]
  config:
    bibtex_reference_style: super
    
bibtex_bibfiles:
    - references.bib

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "force"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

#######################################################################################
# Launch button settings
launch_buttons:
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : By <a href="https://www.tomasbeuzen.com/">Tomas Beuzen</a> & <a href="http://tiffanytimbers.com">Tiffany Timbers</a> # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : "UA-157992550-3"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://py-pkgs.org/"  # The base URL where your book will be hosted.